"""Bộ mẫu guard: 66 query kiểu đề thi trên đủ 13 lĩnh vực + 6 câu cố ý mơ hồ.

Trường `en` là bản enriched TIẾNG ANH LLM thật đã sinh ra (cerebras/gpt-oss-120b,
temperature 0), đóng băng lại tại đây. Nhờ vậy test kiểm đúng module guard một cách
tất định, không gọi mạng và không phụ thuộc LLM còn sống hay không.

Đóng băng cũng có mặt trái: đổi prompt enrich thì `en` ở đây thành cũ. Khi đó chạy lại
scripts thu thập rồi cập nhật file này, ĐỪNG chỉ sửa `exp` cho test xanh — `exp` là
lĩnh vực đúng theo taxonomy ingest, không phải theo cái guard đang trả về.

`exp=None` nghĩa là guard PHẢI trả rỗng: câu quá mơ hồ, lọc cứng vào bất kỳ lĩnh vực
nào cũng là rủi ro mất đáp án.
"""

# (lĩnh vực đúng | None, query tiếng Việt, bản enriched tiếng Anh)
GUARD_SAMPLES: tuple[tuple[str | None, str, str], ...] = (
    # ── politics_society ──────────────────────────────────────────
    ('politics_society', 'hai vị lãnh đạo bắt tay nhau trước hai lá cờ',
     'two leaders shaking hands in front of two flags'),
    ('politics_society', 'người dân xếp hàng chờ làm giấy tờ ở phường',
     'people queuing for paperwork at ward office'),
    ('politics_society', 'một cuộc họp báo với nhiều micro trên bàn',
     'press conference with multiple microphones on the table'),
    ('politics_society', 'đại biểu bấm nút biểu quyết trong hội trường lớn',
     'representative pressing voting button in large hall'),
    ('politics_society', 'lễ ký kết giữa hai đoàn đại biểu',
     'signing ceremony between two delegations'),
    # ── economy_finance ───────────────────────────────────────────
    ('economy_finance', 'nhân viên đếm tiền tại quầy giao dịch',
     'bank teller counting money at a transaction counter'),
    ('economy_finance', 'biểu đồ giá cổ phiếu màu đỏ trên màn hình lớn',
     'red stock price chart on large screen'),
    ('economy_finance', 'người phụ nữ rút tiền ở máy ATM',
     'woman withdrawing money at ATM'),
    ('economy_finance', 'công nhân xếp thùng hàng lên container xuất khẩu',
     'workers loading boxes onto export container'),
    ('economy_finance', 'bảng lãi suất treo trong sảnh ngân hàng',
     'interest rate board hanging in bank lobby'),
    # ── agriculture ───────────────────────────────────────────────
    ('agriculture', 'người đàn ông lái máy cày trên đồng',
     'man driving tractor on field'),
    ('agriculture', 'hai người đang gặt bằng liềm',
     'two people harvesting with sickles'),
    ('agriculture', 'đàn bò được dẫn qua con đường đất',
     'cows being led across a dirt road'),
    ('agriculture', 'người nông dân phun thuốc cho vườn cây',
     'farmer spraying pesticide on garden'),
    ('agriculture', 'công nhân phân loại tôm trong nhà máy',
     'workers sorting shrimp in factory'),
    # ── culture_travel_heritage ───────────────────────────────────
    ('culture_travel_heritage', 'đoàn người mặc áo the khăn xếp rước kiệu',
     'group of people wearing áo the, khăn xếp carrying a sedan chair'),
    ('culture_travel_heritage', 'du khách chụp ảnh trước một toà tháp cổ',
     'tourists photographing ancient tower'),
    ('culture_travel_heritage', 'hai con lân nhảy múa trước cửa hàng',
     'two lân dancing in front of a shop'),
    ('culture_travel_heritage', 'người phụ nữ thắp hương trong chùa',
     'woman lighting incense in chùa'),
    ('culture_travel_heritage', 'phố cổ về đêm treo đầy đèn lồng đỏ',
     'old town at night with red lanterns'),
    # ── science_technology ────────────────────────────────────────
    ('science_technology', 'cánh tay máy đang lắp ráp bảng mạch',
     'robotic arm assembling circuit board'),
    ('science_technology', 'người kỹ sư đeo kính thực tế ảo',
     'engineer wearing virtual reality headset'),
    ('science_technology', 'nhà khoa học nhìn qua kính hiển vi',
     'scientist looking through microscope'),
    ('science_technology', 'dãy tủ máy chủ nhấp nháy đèn xanh',
     'server rack lights blinking green'),
    ('science_technology', 'tấm pin mặt trời trên mái nhà',
     'solar panel on roof'),
    # ── health ────────────────────────────────────────────────────
    ('health', 'bác sĩ mặc áo trắng đo huyết áp cho cụ già',
     'doctor measuring blood pressure on elderly'),
    ('health', 'nhiều người tập dưỡng sinh trong công viên buổi sáng',
     'people practicing dưỡng sinh in a park'),
    ('health', 'điều dưỡng tiêm vaccine cho một em bé',
     'nurse administering vaccine to infant'),
    ('health', 'bệnh nhân nằm trên băng ca được đẩy vào phòng',
     'patient on stretcher being pushed into room'),
    ('health', 'một nhóm người khởi động trước khi chạy',
     'people warming up before running'),
    # ── transport_urban ───────────────────────────────────────────
    ('transport_urban', 'dòng xe kín đặc trên cầu vượt giờ cao điểm',
     'traffic jam on overpass during rush hour'),
    ('transport_urban', 'một chiếc xe tải lật ngang giữa đường',
     'truck overturned on road'),
    ('transport_urban', 'người đi bộ băng qua vạch kẻ đường',
     'pedestrian crossing road line'),
    ('transport_urban', 'xe buýt dừng ở bến đón khách',
     'bus stopping at passenger stop'),
    ('transport_urban', 'cận cảnh biển số một chiếc xe máy',
     'close-up of a motorbike license plate'),
    # ── environment_nature ────────────────────────────────────────
    ('environment_nature', 'nước dâng ngập tới nóc nhà ở vùng quê',
     'water flooding reaching house roofs in rural area'),
    ('environment_nature', 'đàn voọc trên vách đá',
     'macaques on a cliff'),
    ('environment_nature', 'khói đen bốc lên từ một bãi rác',
     'black smoke rising from a garbage dump'),
    ('environment_nature', 'sạt lở làm sập một đoạn đường núi',
     'landslide causing mountain road collapse'),
    ('environment_nature', 'cánh rừng ngập mặn nhìn từ trên cao',
     'mangrove forest aerial view'),
    # ── sports ────────────────────────────────────────────────────
    ('sports', 'vận động viên về đích giơ hai tay',
     'athlete crossing finish line raising both hands'),
    ('sports', 'hai võ sĩ đang giao đấu trên sàn',
     'two fighters battling on a floor'),
    ('sports', 'thủ môn bay người cản phá',
     'goalkeeper diving to block shot'),
    ('sports', 'các tay đua đạp xe theo đoàn trên đường',
     'cyclists riding in a group on a road'),
    ('sports', 'người thắng giải đứng trên bục nhận huy chương',
     'winner standing on podium receiving medal'),
    # ── food_lifestyle ────────────────────────────────────────────
    ('food_lifestyle', 'người bán rong gánh hàng qua phố',
     'street vendor carrying goods across the street'),
    ('food_lifestyle', 'tô phở nóng bốc khói trên bàn',
     'bowl of hot phở steaming on table'),
    ('food_lifestyle', 'đầu bếp đảo chảo trong nhà hàng',
     'chef flipping pan in restaurant'),
    ('food_lifestyle', 'người mua bán ở chợ quê buổi sáng',
     'people buying and selling at a rural market in the morning'),
    ('food_lifestyle', 'buổi trình diễn thời trang trên sàn catwalk',
     'fashion show on catwalk'),
    # ── law_security ──────────────────────────────────────────────
    ('law_security', 'cảnh sát dẫn giải một người bị còng tay',
     'police officer escorting a handcuffed person'),
    ('law_security', 'phiên xét xử trong phòng có vành móng ngựa',
     'courtroom trial, vành móng ngựa'),
    ('law_security', 'công an kiểm tra giấy tờ người đi đường',
     'police checking documents of pedestrians'),
    ('law_security', 'tang vật ma tuý bày trên bàn',
     'drug paraphernalia on a table'),
    ('law_security', 'lực lượng chức năng bắt giữ một nhóm buôn lậu',
     'law enforcement officers arresting smugglers'),
    # ── education ─────────────────────────────────────────────────
    ('education', 'học sinh mặc áo trắng chào cờ giữa sân',
     'students wearing white shirts saluting the flag on the field'),
    ('education', 'thầy giáo viết phấn lên bảng đen',
     'teacher writing chalk on blackboard'),
    ('education', 'thí sinh làm bài trong phòng thi',
     'candidate taking exam in exam room'),
    ('education', 'sinh viên đội mũ tốt nghiệp tung lên trời',
     'students wearing graduation caps throwing them into the air'),
    ('education', 'lớp học trực tuyến trên màn hình máy tính',
     'online class on computer screen'),
    # ── PHẢI RỖNG — mơ hồ ──────────────────────────────────────────────────────
    (None, 'một vật thể màu xanh đang chuyển động',
     'blue object moving'),
    (None, 'hai người đang nói chuyện với nhau',
     'two people talking'),
    (None, 'cận cảnh bàn tay của một người',
     'close-up of a human hand'),
    (None, 'cảnh quay từ trên cao xuống một khu vực',
     'aerial view of area'),
    (None, 'một người mặc áo đỏ đi từ phải sang trái',
     'person wearing red shirt walking left'),
    (None, 'ba người đứng thành hàng ngang',
     'three people standing side by side'),
)
